commonLabels:
  app.kubernetes.io/managed-by: terraform
  app.kubernetes.io/part-of: tfstate-storage
  team: platform

garage:
  replicationFactor: 1

persistence:
  enabled: true
  meta:
    size: 500Mi
    storageClass: "garage-topolvm"
  data:
    size: 5Gi
    storageClass: "garage-topolvm"

deployment:
  replicaCount: 1  
  livenessProbe:
    httpGet:
      path: /health
      port: 3900
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
  readinessProbe:
    httpGet:
      path: /health
      port: 3900
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 5

resources:
  requests:
    memory: "512Mi"
    cpu: "100m"
  limits:
    memory: "1024Mi"
    cpu: "500m"
    

# TODO enable prometheus metrics
